apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-gateway
  namespace: ai-gateway
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
