apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: act-runner-data
  namespace: gitea-runner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-ssd
  resources:
    requests:
      storage: 1Gi
