apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-runner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mihai7785/homelab.git
    targetRevision: HEAD
    path: gitops/apps/gitea-runner
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
