apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8sgpt
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.k8sgpt.ai/
      chart: k8sgpt-operator
      targetRevision: 0.2.25
      helm:
        valueFiles:
          - $values/platform/values/k8sgpt.yaml
    - repoURL: https://github.com/mihai7785/homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/mihai7785/homelab
      targetRevision: HEAD
      path: infrastructure/k8sgpt
  destination:
    server: https://kubernetes.default.svc
    namespace: k8sgpt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
