apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step-ca
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://smallstep.github.io/helm-charts
      chart: step-certificates
      targetRevision: 1.27.4
      helm:
        valueFiles:
          - $values/infrastructure/step-ca/values.yaml
    - repoURL: https://github.com/mihai7785/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: step-ca
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
