apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt
  namespace: k8sgpt
spec:
  ai:
    enabled: true
    model: llama3.1:8b
    backend: localai
    baseUrl: http://192.168.1.94:11434/v1
  noCache: false
  version: v0.3.43
  integrations:
    trivy:
      enabled: false
