apiVersion: v1
kind: Namespace
metadata:
  name: ai-generated

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ai-generated
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/managed-by: ai-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ai-generated
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/managed-by: ai-gateway
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP